In [ ]:
題目:
1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
2.呈上題，將以上數列取出偶數。
3.呈1題，將數列取出3的倍數。

In [9]:
!pip3 install numpy

In [10]:
import numpy as np
np.__version__

'1.19.2'

In [13]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
np.arange(0,21,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [19]:
#2.呈上題，將以上數列取出偶數。
a = np.arange(0,21,1)
a[2:21:2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
#3.呈1題，將數列取出3的倍數。
b = np.arange(0,21,1)
b[3:21:3]

array([ 3,  6,  9, 12, 15, 18])